### ISSUE TITLE
Caching calls to compile function

### ISSUE THREAD

**Issue by pocin** [doloopwhile/pyjq#15]
I am not really sure about the inner workings of `jq`, but I was wondering if caching the calls to the `pyjq.compile` function https://github.com/doloopwhile/pyjq/blob/master/pyjq.py#L11
would improve performance (I am not even sure if this is a bottleneck, though). Something similar to the `re` standard library implementation.

Maybe something as simple as wrapping the `pyjq.compile` function with `@functools.lru_cache` decorator https://docs.python.org/3/library/functools.html#functools.lru_cache might do the trick?

Do you think this makes sense to investigate further?

**Comment by doloopwhile** [comment]
Your suggestion looks correct. Caching ought to improve performance.

However, I do not intent to add caching because I wrote this library just as a practice.
I am going to accept your pull request.
