### ISSUE TITLE
distribute wheels?

### ISSUE THREAD

**Issue by AlJohri** [doloopwhile/pyjq#26]
@doloopwhile would it be possible to distribute wheels with the package for the latest python/macos? currently running `pip install pyjq` requires compilation and thus requires to run `brew install autoconf automake libtool` on macos or the equivalent on other distributions

```
Collecting pyjq
  Using cached https://files.pythonhosted.org/packages/66/74/7f5c7789c894a943088040a0c148f7ac5daddf4096cf820e3ff15ae75ea0/pyjq-2.3.1.tar.gz
Requirement already satisfied: six in /Users/atul/.local/share/virtualenvs/taxonomy-analysis-2guDZYxG/lib/python3.7/site-packages (from pyjq) (1.12.0)
Building wheels for collected packages: pyjq
  Running setup.py bdist_wheel for pyjq ... done
  Stored in directory: /Users/atul/Library/Caches/pip/wheels/78/62/a0/6c56e20094dc02c9070f94a7b06b164cf003168a74ab0b7c0c
Successfully built pyjq
Installing collected packages: pyjq
Successfully installed pyjq-2.3.1
```

this would also resolve #16 for future users and maybe #9

**Comment by doloopwhile** [comment]
I uploaded wheel for macOS.

As you write, If we distributed wheel for Windows, #9 is solved. However, I have not builded pyjq on Windows.
