### ISSUE TITLE
_pyjq.pyx

### ISSUE THREAD

**Issue by dev-dsp** [doloopwhile/pyjq#29]
Why is not _pyjq.pyx file updated along with _pyjq.c? I am having troubles installing pyjq into venv with pipenv running on pypy7:

```
     /usr/bin/mkdir -p '/tmp/pip-install-4e6f_k5b/pyjq/dependencies/jq_install/include'
     /usr/bin/install -c -m 644 jv.h jq.h '/tmp/pip-install-4e6f_k5b/pyjq/dependencies/jq_install/include'
    building '_pyjq' extension
    creating build/temp.linux-x86_64-3.6
    gcc -pthread -DNDEBUG -O2 -fPIC -Idependencies/jq_install/include -I/opt/pypy3/include -c _pyjq.c -o build/temp.linux-x86_64-3.6/_pyjq.o
    _pyjq.c:235: warning: "PyMethod_New" redefined
       #define PyMethod_New(func, self, klass) ((self) ? PyMethod_New(func, self) : PyInstanceMethod_New(func))
    
    In file included from /opt/pypy3/include/Python.h:148,
                     from _pyjq.c:16:
    /opt/pypy3/include/pypy_decl.h:487: note: this is the location of the previous definition
     #define PyMethod_New PyPyMethod_New
    
    _pyjq.c: In function ‘__Pyx_Raise’:
    _pyjq.c:3819:34: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_traceback’
             PyObject* tmp_tb = tstate->curexc_traceback;
                                      ^~
    _pyjq.c:3822:19: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_traceback’
                 tstate->curexc_traceback = tb;
                       ^~
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------

```

When I've cloned latest code and executed cython _pyjq.pyx && python setup.py install && python setup.py test, it got successfully compiled and installed to venv.

**Comment by doloopwhile** [comment]
It is "by design".

We don't have to commit `_pyjq.c`. However, if `_pyjq.c` is not commited, `cython` is required to install pyjq.

**Comment by dev-dsp** [comment]
Hi @doloopwhile. Thanks for your answer.
Then please explain, why here: https://github.com/doloopwhile/pyjq/blob/master/README.rst#we-do-commit-_pyjqc it is stated, that _pyjq.c *should* be committed?

**Comment by doloopwhile** [comment]
> it is stated, that _pyjq.c should be committed?

Yes.

**Comment by doloopwhile** [comment]
> We don't have to commit _pyjq.c.
This sentence was not clear.

What I mean is ..

- In this project, we have to commit `_pyjq.c`.
- In other project, its authors can commit  generated `*.c`. But they may choose not to commit `*.c`. It is just a technical option.
