### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by vreddhi** [doloopwhile/pyjq#42]
pip install pyjq

Above command results in successfull installation after installing libtools in ubuntu. However the final message is 
Successfully installed unknown-0.0.0

**Comment by vreddhi** [comment]
The output clearly says:

WARNING: Generating metadata for package pyjq produced metadata for project name unknown. Fix your #egg=pyjq fragments.

**Comment by doloopwhile** [comment]
Possibly, There might exist unnecessary files in your directories. Please, clean them and retry installation.

**Comment by vreddhi** [comment]
well older version works though.
pip3 install -b build pyjq==2.3.1

There is another machine in which i see the same issue. I will try clean the directories and give it a try again.
