### ISSUE TITLE
An installation problem in 2.4.0

### ISSUE THREAD

**Issue by ymoch** [doloopwhile/pyjq#43]
Version 2.4.0 depends on `six` but this is not declared in `setup.py`, which causes an installation problem in my environment.
https://github.com/doloopwhile/pyjq/blob/v2.4.0/pyjq.py#L4

I suppose that this problem has been fixed in the master. So I hope this fix would be released in a new version.

**Comment by doloopwhile** [comment]
Removed `six` in new version.
