### ISSUE TITLE
Make ScriptRuntimeError importable from the pyjq module

### ISSUE THREAD

**Issue by SaschaSchlemmer** [doloopwhile/pyjq#45]
It'd be nice if one could import `ScriptRuntimeError` from the pyjq module.
```python
from pyjq import ScriptRuntimeError
```

currently one has to import use `pyjq._pyjq.ScriptRuntimeError`. 

---

As an alternative pyjq could issue plain `RuntimeError` instead of creating a custom Exception.

**Comment by doloopwhile** [comment]
I have done it.
