### ISSUE TITLE
Error during installation on mac

### ISSUE THREAD

**Issue by Krazybug** [doloopwhile/pyjq#50]
Here is the error message:
```   
 subprocess.CalledProcessError: Command '['autoreconf', '-i']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/nnnnnn/Library/Caches/pypoetry/virtualenvs/calisuck-O85FJhRa-py3.8/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/yr/9063jpx93jjf653zp9f509gr0000gp/T/pip-install-1v9maak5/pyjq/setup.py'"'"'; __file__='"'"'/private/var/folders/yr/9063jpx93jjf653zp9f509gr0000gp/T/pip-install-1v9maak5/pyjq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/yr/9063jpx93jjf653zp9f509gr0000gp/T/pip-record-g6lne1ur/install-record.txt --single-version-externally-managed --compile --install-headers /Users/nnnnn/Library/Caches/pypoetry/virtualenvs/calisuck-O85FJhRa-py3.8/include/site/python3.8/pyjq Check the logs for full command output.
```

Same issue with old versions

**Comment by dsielert** [comment]
brew install autoconf libtool fixes this for me

**Comment by Krazybug** [comment]
Thanks for the tip. It doesn't change anything for me.

**Comment by cspargo-apria** [comment]
I was getting similar error in Ubuntu 20.04.1 LTS
`    error: [Errno 2] No such file or directory: 'autoreconf'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u1crke1o/pyjq/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u1crke1o/pyjq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3chl7die/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/cls/.local/include/python3.8/pyjq Check the logs for full command output.`

Thanks to @dsielert comment I tried `apt install autoconf libtool`, then pyjq installed correctly.
