### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by johnflavin** [doloopwhile/pyjq#52]
Hi,

I would like to be able to install this package with conda via conda-forge.

I am willing to create the recipe and submit it to conda-forge by following [this guide](https://conda-forge.org/#add_recipe). It won't be much work to create, just a few minutes.

But while I can create the recipe, I'm not sure I want to be on the hook for maintaining the recipe 😬 . Really, the only maintenance would be keeping the conda recipe up-to-date with any new version releases or dependency changes. As in, when you push a new version to pypi, just update the conda-forge recipe as well.

Are there any maintainers here who would be willing to fill the role of maintainer of the conda-forge recipe?

**Comment by doloopwhile** [comment]
I have not use conda and I am not going to use it too. I do not intent to pay cost to create conda-forge recipe.

So, you may create recpie and become auther if possible.
