### ISSUE TITLE
how do I install pyjq on python running on windows?

### ISSUE THREAD

**Issue by mewalig** [doloopwhile/pyjq#9]
`easy_install install pyjq` doesn't work (nor does `pip`). It appears to be attempting a unix-like build process on a windows machine.

Tried cross-compiling from a unix-like environment (OSX) and seemed to start working, but it gets hung up on a missing "processenv.h" which means I'll need an updated version of mingw64 to get that header (or edit the code to not require that header). updated mingw on darwin has no autobuild, so I'll have to rebuild my own.

So before I embark on this potentially multi-hour experiment of modifying the build code or recompiling my cross-compiler... has anyone already done this (install pyjq on Win-based python) and if so could you please advise?

**Comment by mewalig** [comment]
someone's hiring to solve this: https://www.upwork.com/jobs/~0147f3bb893b8bb615

**Comment by doloopwhile** [comment]
Thanks for your reporting.
But I have not compile the jq command on windows (not only pyjq).

**Comment by aliencoder16** [comment]
I am am having a problem with installing it via pip on a windows machine, this is the error I get

C:\Users\MY_USER>pip install pyjq
Collecting pyjq
  Using cached pyjq-2.1.0.tar.gz
Requirement already satisfied: six in c:\python3\lib\site-packages (from pyjq)
Installing collected packages: pyjq
  Running setup.py install for pyjq ... error
    Complete output from command c:\python3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\MY_USER\\AppData\\Local\\Temp\\pip-build-k7cnpd5a\\pyjq\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\MY_USER\AppData\Local\Temp\pip-g3tkaopx-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    copying pyjq.py -> build\lib.win-amd64-3.6
    running build_ext
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\python3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\MY_USER\\AppData\\Local\\Temp\\pip-build-k7cnpd5a\\pyjq\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\MY_USER\AppData\Local\Temp\pip-g3tkaopx-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\MY_USER\AppData\Local\Temp\pip-build-k7cnpd5a\pyjq\

**Comment by yrfu** [comment]
I got the same error as @aliencoder16 above on Windows 7 and python 3.6.5. Anyway to resolve this?

**Comment by williballenthin** [comment]
The above error appears to happen because the current working directory is not correctly set when invoking `./configure` on the bundled oniguruma library. Unfortunately, once this is fixed, the library still will not compile, because it relies on a `configure` shell script (which Windows won't understand). Some effort would be required to port the compilation steps to a Windows build environment.

**Comment by doloopwhile** [comment]
I should release a  wheel for Windows.

**Comment by doloopwhile** [comment]
I close this issue because there are no prospects to resolve.

**Comment by theaniketpatil03** [comment]
I think you haven't released pyjq wheel for windows
